<a href="https://colab.research.google.com/github/smhasandanish/codsoft-datasci-internship/blob/main/codsoft_taskno_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving IRIS.xlsx to IRIS.xlsx


In [ ]:
# Step 1: Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import plotly.express as px

# Step 2: Load the Iris dataset from your computer
iris_data = pd.read_excel('IRIS.xlsx')

# Step 3: Data preprocessing
# Splitting the dataset into features (X) and target (y)
X = iris_data.drop('species', axis=1)
y = iris_data['species']

# Split the dataset into a training set and a testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the feature data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 4: Train a machine learning model
# In this example, we'll use a k-nearest neighbors (KNN) classifier.
k = 3
classifier = KNeighborsClassifier(n_neighbors=k)
classifier.fit(X_train, y_train)

# Step 5: Make predictions on the test data
y_pred = classifier.predict(X_test)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Step 7: Display the results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

# Step 9: Visualize the data
fig = px.scatter(iris_data, x="sepal_width", y="sepal_length", color="species")
fig.show()


Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
# Step 8: Make a prediction using the trained KNN model
x_new = np.array([[5, 2.9, 1, 0.2]])
prediction = classifier.predict(x_new)
print("Prediction: {}".format(prediction))

Prediction: ['Iris-virginica']
